# Generated by Django 4.2.1 on 2023-06-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
