# Generated by Django 4.2.1 on 2023-06-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='mobile',
            field=models.IntegerField(help_text='Enter 10 digits phone number', unique=True, verbose_name='Phone Number'),
        ),
    ]
