# Generated by Django 4.2.1 on 2023-06-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_phone_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
